apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
 labels:
   prometheus: example-rules
   role: alert-rules
 name: prom
spec:
  groups:
  - name: example
    rules:
    - alert: HighRequestRate
      expr: http_server_requests_seconds_count>100
      for: 15s
      labels:
        severity: critical
      annotations:
        summary: High request rate detected
        description: '{{ $labels.instance }} has a high request rate ({{ $value }} requests/5m).'
    - alert: BlackboxProbeFailed
      expr: probe_success == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Blackbox probe failed (instance {{ $labels.instance }})
        description: "Probe failed\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: BlackboxProbeHttpFailure
      expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Blackbox probe HTTP failure (instance {{ $labels.instance }})
        description: "HTTP status code is not 200-399\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
