apiVersion: v1
kind: Service
metadata:
  name: service-webhook
spec:
  type: NodePort
  selector:
    app: webhook-python
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 31000  
